-- Real Dhaka service geography, transcribed from
-- service_area_details_inhouse_sheba_md.md. Idempotent: every statement
-- upserts by name, so re-running this after an edit to the source updates
-- zone/sort assignments rather than duplicating rows.

-- The pre-existing area used a shorter name for the same real place.
UPDATE areas SET name = 'Bashundhara Residential Area (R/A)' WHERE name = 'Bashundhara R/A' AND NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Bashundhara Residential Area (R/A)');

-- Zones
INSERT INTO zones (name, sort, active) VALUES ('Central Dhaka', 1, 1) ON CONFLICT(name) DO UPDATE SET sort = excluded.sort;
INSERT INTO zones (name, sort, active) VALUES ('Old Dhaka', 2, 1) ON CONFLICT(name) DO UPDATE SET sort = excluded.sort;
INSERT INTO zones (name, sort, active) VALUES ('Northern Dhaka', 3, 1) ON CONFLICT(name) DO UPDATE SET sort = excluded.sort;
INSERT INTO zones (name, sort, active) VALUES ('Southern Dhaka', 4, 1) ON CONFLICT(name) DO UPDATE SET sort = excluded.sort;
INSERT INTO zones (name, sort, active) VALUES ('Eastern Dhaka', 5, 1) ON CONFLICT(name) DO UPDATE SET sort = excluded.sort;
INSERT INTO zones (name, sort, active) VALUES ('Western Dhaka', 6, 1) ON CONFLICT(name) DO UPDATE SET sort = excluded.sort;
INSERT INTO zones (name, sort, active) VALUES ('Suburban Dhaka', 7, 1) ON CONFLICT(name) DO UPDATE SET sort = excluded.sort;

-- Areas (upsert by name; assigns/updates zone_id and sort)
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Motijheel', (SELECT id FROM zones WHERE name = 'Central Dhaka'), 1, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Motijheel');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Central Dhaka'), sort = 1 WHERE name = 'Motijheel';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Paltan', (SELECT id FROM zones WHERE name = 'Central Dhaka'), 2, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Paltan');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Central Dhaka'), sort = 2 WHERE name = 'Paltan';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Shahbagh', (SELECT id FROM zones WHERE name = 'Central Dhaka'), 3, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Shahbagh');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Central Dhaka'), sort = 3 WHERE name = 'Shahbagh';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Ramna', (SELECT id FROM zones WHERE name = 'Central Dhaka'), 4, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Ramna');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Central Dhaka'), sort = 4 WHERE name = 'Ramna';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Azimpur', (SELECT id FROM zones WHERE name = 'Central Dhaka'), 5, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Azimpur');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Central Dhaka'), sort = 5 WHERE name = 'Azimpur';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Lalbagh', (SELECT id FROM zones WHERE name = 'Old Dhaka'), 6, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Lalbagh');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Old Dhaka'), sort = 6 WHERE name = 'Lalbagh';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Chawkbazar', (SELECT id FROM zones WHERE name = 'Old Dhaka'), 7, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Chawkbazar');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Old Dhaka'), sort = 7 WHERE name = 'Chawkbazar';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Sutrapur', (SELECT id FROM zones WHERE name = 'Old Dhaka'), 8, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Sutrapur');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Old Dhaka'), sort = 8 WHERE name = 'Sutrapur';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Kotwali', (SELECT id FROM zones WHERE name = 'Old Dhaka'), 9, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Kotwali');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Old Dhaka'), sort = 9 WHERE name = 'Kotwali';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Uttara', (SELECT id FROM zones WHERE name = 'Northern Dhaka'), 10, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Uttara');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Northern Dhaka'), sort = 10 WHERE name = 'Uttara';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Sector 1–6', (SELECT id FROM zones WHERE name = 'Northern Dhaka'), 11, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Sector 1–6');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Northern Dhaka'), sort = 11 WHERE name = 'Sector 1–6';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Sector 7–12', (SELECT id FROM zones WHERE name = 'Northern Dhaka'), 12, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Sector 7–12');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Northern Dhaka'), sort = 12 WHERE name = 'Sector 7–12';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Sector 13–18', (SELECT id FROM zones WHERE name = 'Northern Dhaka'), 13, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Sector 13–18');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Northern Dhaka'), sort = 13 WHERE name = 'Sector 13–18';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Tongi', (SELECT id FROM zones WHERE name = 'Northern Dhaka'), 14, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Tongi');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Northern Dhaka'), sort = 14 WHERE name = 'Tongi';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Mirpur', (SELECT id FROM zones WHERE name = 'Northern Dhaka'), 15, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Mirpur');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Northern Dhaka'), sort = 15 WHERE name = 'Mirpur';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Sections 1–2', (SELECT id FROM zones WHERE name = 'Northern Dhaka'), 16, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Sections 1–2');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Northern Dhaka'), sort = 16 WHERE name = 'Sections 1–2';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Sections 6–7', (SELECT id FROM zones WHERE name = 'Northern Dhaka'), 17, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Sections 6–7');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Northern Dhaka'), sort = 17 WHERE name = 'Sections 6–7';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Sections 10–12', (SELECT id FROM zones WHERE name = 'Northern Dhaka'), 18, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Sections 10–12');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Northern Dhaka'), sort = 18 WHERE name = 'Sections 10–12';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Pallabi', (SELECT id FROM zones WHERE name = 'Northern Dhaka'), 19, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Pallabi');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Northern Dhaka'), sort = 19 WHERE name = 'Pallabi';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Banani', (SELECT id FROM zones WHERE name = 'Northern Dhaka'), 20, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Banani');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Northern Dhaka'), sort = 20 WHERE name = 'Banani';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Gulshan', (SELECT id FROM zones WHERE name = 'Northern Dhaka'), 21, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Gulshan');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Northern Dhaka'), sort = 21 WHERE name = 'Gulshan';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Jatrabari', (SELECT id FROM zones WHERE name = 'Southern Dhaka'), 22, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Jatrabari');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Southern Dhaka'), sort = 22 WHERE name = 'Jatrabari';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Demra', (SELECT id FROM zones WHERE name = 'Southern Dhaka'), 23, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Demra');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Southern Dhaka'), sort = 23 WHERE name = 'Demra';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Shyampur', (SELECT id FROM zones WHERE name = 'Southern Dhaka'), 24, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Shyampur');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Southern Dhaka'), sort = 24 WHERE name = 'Shyampur';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Keraniganj (Inner)', (SELECT id FROM zones WHERE name = 'Southern Dhaka'), 25, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Keraniganj (Inner)');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Southern Dhaka'), sort = 25 WHERE name = 'Keraniganj (Inner)';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Bashundhara Residential Area (R/A)', (SELECT id FROM zones WHERE name = 'Eastern Dhaka'), 26, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Bashundhara Residential Area (R/A)');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Eastern Dhaka'), sort = 26 WHERE name = 'Bashundhara Residential Area (R/A)';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Banasree', (SELECT id FROM zones WHERE name = 'Eastern Dhaka'), 27, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Banasree');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Eastern Dhaka'), sort = 27 WHERE name = 'Banasree';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Rampura', (SELECT id FROM zones WHERE name = 'Eastern Dhaka'), 28, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Rampura');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Eastern Dhaka'), sort = 28 WHERE name = 'Rampura';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Khilgaon', (SELECT id FROM zones WHERE name = 'Eastern Dhaka'), 29, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Khilgaon');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Eastern Dhaka'), sort = 29 WHERE name = 'Khilgaon';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Aftabnagar', (SELECT id FROM zones WHERE name = 'Eastern Dhaka'), 30, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Aftabnagar');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Eastern Dhaka'), sort = 30 WHERE name = 'Aftabnagar';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Malibagh', (SELECT id FROM zones WHERE name = 'Eastern Dhaka'), 31, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Malibagh');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Eastern Dhaka'), sort = 31 WHERE name = 'Malibagh';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Mohammadpur', (SELECT id FROM zones WHERE name = 'Western Dhaka'), 32, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Mohammadpur');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Western Dhaka'), sort = 32 WHERE name = 'Mohammadpur';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Dhanmondi', (SELECT id FROM zones WHERE name = 'Western Dhaka'), 33, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Dhanmondi');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Western Dhaka'), sort = 33 WHERE name = 'Dhanmondi';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Lalmatia', (SELECT id FROM zones WHERE name = 'Western Dhaka'), 34, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Lalmatia');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Western Dhaka'), sort = 34 WHERE name = 'Lalmatia';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Adabor', (SELECT id FROM zones WHERE name = 'Western Dhaka'), 35, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Adabor');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Western Dhaka'), sort = 35 WHERE name = 'Adabor';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Savar', (SELECT id FROM zones WHERE name = 'Suburban Dhaka'), 36, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Savar');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Suburban Dhaka'), sort = 36 WHERE name = 'Savar';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Ashulia', (SELECT id FROM zones WHERE name = 'Suburban Dhaka'), 37, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Ashulia');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Suburban Dhaka'), sort = 37 WHERE name = 'Ashulia';
INSERT INTO areas (name, zone_id, sort, active) SELECT 'Keraniganj (Outer)', (SELECT id FROM zones WHERE name = 'Suburban Dhaka'), 38, 1 WHERE NOT EXISTS (SELECT 1 FROM areas WHERE name = 'Keraniganj (Outer)');
UPDATE areas SET zone_id = (SELECT id FROM zones WHERE name = 'Suburban Dhaka'), sort = 38 WHERE name = 'Keraniganj (Outer)';

-- Locations (guarded against duplicate area+name pairs, so this stays idempotent)
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Dilkusha', 1, 1 FROM areas WHERE name = 'Motijheel' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Dilkusha');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Arambagh', 2, 1 FROM areas WHERE name = 'Motijheel' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Arambagh');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Fakirapool', 3, 1 FROM areas WHERE name = 'Motijheel' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Fakirapool');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Inner Circular Road', 4, 1 FROM areas WHERE name = 'Motijheel' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Inner Circular Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'VIP Road', 1, 1 FROM areas WHERE name = 'Paltan' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'VIP Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Nayapaltan', 2, 1 FROM areas WHERE name = 'Paltan' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Nayapaltan');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Kakrail', 3, 1 FROM areas WHERE name = 'Paltan' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Kakrail');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Bijoy Nagar', 4, 1 FROM areas WHERE name = 'Paltan' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Bijoy Nagar');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Katabon', 1, 1 FROM areas WHERE name = 'Shahbagh' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Katabon');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Elephant Road', 2, 1 FROM areas WHERE name = 'Shahbagh' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Elephant Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Aziz Super Market', 3, 1 FROM areas WHERE name = 'Shahbagh' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Aziz Super Market');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Dhaka University Area', 4, 1 FROM areas WHERE name = 'Shahbagh' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Dhaka University Area');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Segunbagicha', 1, 1 FROM areas WHERE name = 'Ramna' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Segunbagicha');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Bailey Road', 2, 1 FROM areas WHERE name = 'Ramna' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Bailey Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Minto Road', 3, 1 FROM areas WHERE name = 'Ramna' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Minto Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Azimpur Colony', 1, 1 FROM areas WHERE name = 'Azimpur' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Azimpur Colony');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Plassey', 2, 1 FROM areas WHERE name = 'Azimpur' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Plassey');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'New Market Area', 3, 1 FROM areas WHERE name = 'Azimpur' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'New Market Area');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Nilkhet', 4, 1 FROM areas WHERE name = 'Azimpur' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Nilkhet');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Hazaribagh', 1, 1 FROM areas WHERE name = 'Lalbagh' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Hazaribagh');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Posta', 2, 1 FROM areas WHERE name = 'Lalbagh' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Posta');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Churihatta', 3, 1 FROM areas WHERE name = 'Lalbagh' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Churihatta');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Nawabganj Road', 4, 1 FROM areas WHERE name = 'Lalbagh' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Nawabganj Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Alu Bazar', 1, 1 FROM areas WHERE name = 'Chawkbazar' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Alu Bazar');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Laxmibazar', 2, 1 FROM areas WHERE name = 'Chawkbazar' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Laxmibazar');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Urdu Road', 3, 1 FROM areas WHERE name = 'Chawkbazar' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Urdu Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Gandaria', 1, 1 FROM areas WHERE name = 'Sutrapur' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Gandaria');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Islambagh', 2, 1 FROM areas WHERE name = 'Sutrapur' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Islambagh');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Farashganj', 3, 1 FROM areas WHERE name = 'Sutrapur' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Farashganj');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Sadarghat', 1, 1 FROM areas WHERE name = 'Kotwali' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Sadarghat');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Ahsan Manzil', 2, 1 FROM areas WHERE name = 'Kotwali' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Ahsan Manzil');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Bangshal', 3, 1 FROM areas WHERE name = 'Kotwali' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Bangshal');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Mitford', 4, 1 FROM areas WHERE name = 'Kotwali' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Mitford');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Azampur', 1, 1 FROM areas WHERE name = 'Sector 1–6' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Azampur');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Jashimuddin Road', 2, 1 FROM areas WHERE name = 'Sector 1–6' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Jashimuddin Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Airport Road', 3, 1 FROM areas WHERE name = 'Sector 1–6' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Airport Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Abdullahpur', 1, 1 FROM areas WHERE name = 'Sector 7–12' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Abdullahpur');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Ashkona', 2, 1 FROM areas WHERE name = 'Sector 7–12' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Ashkona');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Rajlakkhi', 3, 1 FROM areas WHERE name = 'Sector 7–12' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Rajlakkhi');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Nikunja-1', 1, 1 FROM areas WHERE name = 'Sector 13–18' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Nikunja-1');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Nikunja-2', 2, 1 FROM areas WHERE name = 'Sector 13–18' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Nikunja-2');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Uttarkhan', 3, 1 FROM areas WHERE name = 'Sector 13–18' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Uttarkhan');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Dakshinkhan', 4, 1 FROM areas WHERE name = 'Sector 13–18' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Dakshinkhan');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Station Road', 1, 1 FROM areas WHERE name = 'Tongi' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Station Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Mill Gate', 2, 1 FROM areas WHERE name = 'Tongi' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Mill Gate');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Cherag Ali', 3, 1 FROM areas WHERE name = 'Tongi' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Cherag Ali');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Tongi Bazaar', 4, 1 FROM areas WHERE name = 'Tongi' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Tongi Bazaar');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Agargaon', 1, 1 FROM areas WHERE name = 'Sections 1–2' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Agargaon');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Zoo Road', 2, 1 FROM areas WHERE name = 'Sections 1–2' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Zoo Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Rupnagar', 1, 1 FROM areas WHERE name = 'Sections 6–7' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Rupnagar');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Monipur', 2, 1 FROM areas WHERE name = 'Sections 6–7' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Monipur');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Pallabi', 1, 1 FROM areas WHERE name = 'Sections 10–12' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Pallabi');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Kalshi', 2, 1 FROM areas WHERE name = 'Sections 10–12' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Kalshi');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Mirpur DOHS', 3, 1 FROM areas WHERE name = 'Sections 10–12' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Mirpur DOHS');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Kazipara', 1, 1 FROM areas WHERE name = 'Pallabi' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Kazipara');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Shewrapara', 2, 1 FROM areas WHERE name = 'Pallabi' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Shewrapara');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Taltola', 3, 1 FROM areas WHERE name = 'Pallabi' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Taltola');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Banani DOHS', 1, 1 FROM areas WHERE name = 'Banani' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Banani DOHS');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Kemal Ataturk Avenue', 2, 1 FROM areas WHERE name = 'Banani' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Kemal Ataturk Avenue');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Block A–H', 3, 1 FROM areas WHERE name = 'Banani' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Block A–H');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Gulshan 1', 1, 1 FROM areas WHERE name = 'Gulshan' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Gulshan 1');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Gulshan 2', 2, 1 FROM areas WHERE name = 'Gulshan' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Gulshan 2');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Gulshan Avenue', 3, 1 FROM areas WHERE name = 'Gulshan' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Gulshan Avenue');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Baridhara', 4, 1 FROM areas WHERE name = 'Gulshan' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Baridhara');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Dholairpar', 1, 1 FROM areas WHERE name = 'Jatrabari' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Dholairpar');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Kajla', 2, 1 FROM areas WHERE name = 'Jatrabari' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Kajla');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Kutubkhali', 3, 1 FROM areas WHERE name = 'Jatrabari' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Kutubkhali');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Shahid Faruk Road', 4, 1 FROM areas WHERE name = 'Jatrabari' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Shahid Faruk Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Matuail', 1, 1 FROM areas WHERE name = 'Demra' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Matuail');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Konapara', 2, 1 FROM areas WHERE name = 'Demra' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Konapara');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Sarulia', 3, 1 FROM areas WHERE name = 'Demra' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Sarulia');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Demra Staff Quarter', 4, 1 FROM areas WHERE name = 'Demra' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Demra Staff Quarter');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Jurain', 1, 1 FROM areas WHERE name = 'Shyampur' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Jurain');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Pagla', 2, 1 FROM areas WHERE name = 'Shyampur' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Pagla');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Postogola', 3, 1 FROM areas WHERE name = 'Shyampur' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Postogola');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Titas Road', 4, 1 FROM areas WHERE name = 'Shyampur' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Titas Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Kalatia', 1, 1 FROM areas WHERE name = 'Keraniganj (Inner)' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Kalatia');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Zinjira', 2, 1 FROM areas WHERE name = 'Keraniganj (Inner)' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Zinjira');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Shubhadya', 3, 1 FROM areas WHERE name = 'Keraniganj (Inner)' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Shubhadya');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Aganagar', 4, 1 FROM areas WHERE name = 'Keraniganj (Inner)' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Aganagar');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Block A–N', 1, 1 FROM areas WHERE name = 'Bashundhara Residential Area (R/A)' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Block A–N');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Jamuna Future Park Area', 2, 1 FROM areas WHERE name = 'Bashundhara Residential Area (R/A)' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Jamuna Future Park Area');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Block A–J', 1, 1 FROM areas WHERE name = 'Banasree' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Block A–J');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'South Banasree', 2, 1 FROM areas WHERE name = 'Banasree' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'South Banasree');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Merul Badda', 3, 1 FROM areas WHERE name = 'Banasree' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Merul Badda');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Chowdhury Para', 1, 1 FROM areas WHERE name = 'Rampura' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Chowdhury Para');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'East Rampura', 2, 1 FROM areas WHERE name = 'Rampura' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'East Rampura');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'West Rampura', 3, 1 FROM areas WHERE name = 'Rampura' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'West Rampura');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Goran', 1, 1 FROM areas WHERE name = 'Khilgaon' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Goran');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Taltola', 2, 1 FROM areas WHERE name = 'Khilgaon' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Taltola');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Khilgaon Railgate', 3, 1 FROM areas WHERE name = 'Khilgaon' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Khilgaon Railgate');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Tilpapara', 4, 1 FROM areas WHERE name = 'Khilgaon' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Tilpapara');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Block A–H', 1, 1 FROM areas WHERE name = 'Aftabnagar' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Block A–H');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Lake City', 2, 1 FROM areas WHERE name = 'Aftabnagar' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Lake City');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Aftabnagar Link Road', 3, 1 FROM areas WHERE name = 'Aftabnagar' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Aftabnagar Link Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Malibagh Chowdhury Para', 1, 1 FROM areas WHERE name = 'Malibagh' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Malibagh Chowdhury Para');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Shantinagar', 2, 1 FROM areas WHERE name = 'Malibagh' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Shantinagar');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Mouchak', 3, 1 FROM areas WHERE name = 'Malibagh' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Mouchak');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Shyamoli', 1, 1 FROM areas WHERE name = 'Mohammadpur' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Shyamoli');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Kaderabad Housing', 2, 1 FROM areas WHERE name = 'Mohammadpur' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Kaderabad Housing');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Bosila', 3, 1 FROM areas WHERE name = 'Mohammadpur' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Bosila');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Town Hall', 4, 1 FROM areas WHERE name = 'Mohammadpur' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Town Hall');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Road 2–32', 1, 1 FROM areas WHERE name = 'Dhanmondi' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Road 2–32');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Satmasjid Road', 2, 1 FROM areas WHERE name = 'Dhanmondi' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Satmasjid Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Rapa Plaza Area', 3, 1 FROM areas WHERE name = 'Dhanmondi' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Rapa Plaza Area');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Block A–F', 1, 1 FROM areas WHERE name = 'Lalmatia' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Block A–F');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Nurjahan Road', 2, 1 FROM areas WHERE name = 'Lalmatia' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Nurjahan Road');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'PC Culture Housing', 1, 1 FROM areas WHERE name = 'Adabor' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'PC Culture Housing');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Japan Garden City', 2, 1 FROM areas WHERE name = 'Adabor' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Japan Garden City');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Bashbari', 3, 1 FROM areas WHERE name = 'Adabor' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Bashbari');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Aminbazar', 1, 1 FROM areas WHERE name = 'Savar' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Aminbazar');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Nabinagar', 2, 1 FROM areas WHERE name = 'Savar' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Nabinagar');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Savar Cantonment', 3, 1 FROM areas WHERE name = 'Savar' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Savar Cantonment');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Hemayetpur', 4, 1 FROM areas WHERE name = 'Savar' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Hemayetpur');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Fantasy Kingdom Area', 1, 1 FROM areas WHERE name = 'Ashulia' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Fantasy Kingdom Area');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Zirabo', 2, 1 FROM areas WHERE name = 'Ashulia' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Zirabo');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Jamgora', 3, 1 FROM areas WHERE name = 'Ashulia' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Jamgora');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Baipayl', 4, 1 FROM areas WHERE name = 'Ashulia' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Baipayl');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Hasnabad', 1, 1 FROM areas WHERE name = 'Keraniganj (Outer)' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Hasnabad');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Rajendrapur', 2, 1 FROM areas WHERE name = 'Keraniganj (Outer)' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Rajendrapur');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Kaliganj', 3, 1 FROM areas WHERE name = 'Keraniganj (Outer)' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Kaliganj');
INSERT INTO locations (area_id, name, sort, active) SELECT id, 'Agla', 4, 1 FROM areas WHERE name = 'Keraniganj (Outer)' AND NOT EXISTS (SELECT 1 FROM locations l WHERE l.area_id = areas.id AND l.name = 'Agla');
